### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget when running main.py on Windows

### ISSUE THREAD

**Issue by fussballpurpodcast-ux** [nazirlouis/ada_local#9]
First of all: thanks for sharing this project – the router and backend parts are working great locally.

However, starting the GUI through main.py on Windows always fails with

text
QWidget: Must construct a QApplication before a QWidget

even though main.py correctly creates a QApplication before any window is instantiated.
Environment

    OS: Windows (10/11, 64‑bit)

    Python: 3.12 (installed from python.org)

    Hardware: CPU only (Ollama models on CPU), but GPU is not relevant for this error

Ollama:

bash
ollama list

returns for example:

text
qwen3.5:4b    (3.4 GB)
llama3:latest (4.7 GB)

so local models are installed and working.
Installation steps

    Clone the repository:

    bash
    git clone https://github.com/nazirlouis/ada_local.git
    cd ada_local-main   # local folder name

    Install dependencies (no Conda, just system Python 3.12):

    bash
    py -3.12 -m pip install -r requirements.txt

    Install additional packages required by the project:

    bash
    py -3.12 -m pip install python-kasa ddgs markdown playwright
    py -3.12 -m playwright install
    # (and also tried: py -3.12 -m playwright install chromium)

    Router test:

    bash
    py -3.12 -m core.router

    This loads the FunctionGemma router, downloads nlouis/pocket-ai-router on first run, and then prints e.g.:

    text
    Accuracy: 20/21 (95%)
    Average routing time: ~1400ms per prompt

    So the router works fine.

    Settings import test:

    bash
    py -3.12 test_settings.py

    test_settings.py creates a QApplication([]), imports SettingsTab, and prints:

    text
    Import successful

    Immediately after that, this line appears:

    text
    QWidget: Must construct a QApplication before a QWidget

    The import itself succeeds, which suggests the Qt warning is not fatal in this script, but it shows that somewhere in the import chain a QWidget is created at a bad time.

How I start the GUI

From the project root:

bash
cd "C:\Users\User\Desktop\ada_local-main"
py -3.12 main.py

Console output:

text
📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

...\core\news.py:11: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  self.ddgs = DDGS()
...\core\news.py:11: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  self.ddgs = DDGS()
QWidget: Must construct a QApplication before a QWidget

No further traceback, no window opens.
What I have already checked

1. main.py

main.py looks structurally correct:

    It imports QApplication, MainWindow, QFluentWidgets’ SplashScreen, etc.

    Inside if __name__ == "__main__": it does:

        app = QApplication(sys.argv)

        sets theme and font

        creates a SplashScreen

        creates MainWindow()

        shows window and splash

        sys.exit(app.exec())

So the QApplication is definitely created before MainWindow() in this file.

2. gui/app.py

    Defines MainWindow(FluentWindow) and helper classes.

    No QWidget/MainWindow instances are created on module level.

    All widgets are created inside __init__ or methods (e.g. _init_window, _init_system_monitor, etc.).

So gui/app.py also seems safe with respect to “no QWidget before QApplication”.

3. Tabs and components

I inspected several modules that are imported from gui.app:

    gui/tabs/dashboard.py

    gui/tabs/chat.py

    gui/tabs/briefing.py

    gui/components/system_monitor.py

All of them:

    Define classes (DashboardView, ChatTab, BriefingView, SystemMonitor).

    Create Qt widgets only inside __init__ or class methods.

    Do not create widget instances on module level.

So those files alone should not cause the error.

4. Components package gui/components/__init__.py

That file currently does:

python
from gui.components.message_bubble import MessageBubble
from gui.components.thinking_expander import ThinkingExpander
from gui.components.search_indicator import SearchIndicator
from gui.components.toggle_switch import ToggleSwitch
from gui.components.toast import ToastNotification
from gui.components.voice_indicator import VoiceIndicator

__all__ = [
    "MessageBubble",
    "ThinkingExpander",
    "SearchIndicator",
    "ToggleSwitch",
    "ToastNotification",
    "VoiceIndicator",
]

As an experiment, I temporarily replaced the contents of this file with:

python
__all__ = []

Result:

    Running py -3.12 main.py then fails earlier with:

    text
    ImportError: cannot import name 'ThinkingExpander' from 'gui.components'

    (because ChatTab imports ThinkingExpander from gui.components).

    This shows that the GUI init does reach the point of importing gui.components, and that changing __init__.py changes the behavior.
    It suggests that the original QWidget: Must construct a QApplication before a QWidget is very likely triggered by one of the component modules imported via gui.components during module import time (before QApplication is created).

I have not yet identified a specific component file that creates a Qt widget at import time, but the symptoms strongly point in that direction.
Summary

    Backend and router (core.router) work perfectly.

    All required external packages are installed (Playwright, markdown, ddgs, python‑kasa, etc.).

    test_settings.py can import SettingsTab and prints “Import successful”.

    Running main.py on Windows with Python 3.12 consistently ends with:

    text
    QWidget: Must construct a QApplication before a QWidget

    and no GUI appears, even though QApplication is created in main.py before MainWindow().

Given the above, it seems there is a Qt initialization issue somewhere in the import chain (probably via gui.components), where a QWidget gets instantiated before QApplication exists.
Question

Could you please:

    Confirm whether the current main branch is expected to work on Windows/Python 3.12, and

    Check if any of the component/tab modules instantiate Qt widgets on module import?

If you need more logs or are interested in testing a specific branch/commit, I’m happy to try that and report back.
